import Foundation

enum MailRepository {
    static func fetchMails() -> [Mail] {
        return [.init(id: UUID(uuidString: "11e8382c-f66a-4ffb-bd7f-dccff10db196")!,
                      sender: "山田 太郎 <yamada@example.com>",
                      recipient: "鈴木 花子 <suzuki@example.com>",
                      subject: "会議のお知らせ",
                      body: "来週月曜日に予定している会議についての詳細を共有します。",
                      isRead: false,
                      timestamp: Date(timeIntervalSinceNow: 0)),
                .init(id: UUID(uuidString: "4a0151c4-7ba5-4008-8b52-1e4e90f4ef33")!,
                      sender: "田中 次郎 <tanaka@example.com>",
                      recipient: "佐藤 優子 <sato@example.com>",
                      subject: "プロジェクトの進捗確認",
                      body: "現在のプロジェクトの進捗状況を共有していただけますか？",
                      isRead: false,
                      timestamp: Date(timeIntervalSinceNow: -3600)),
                .init(id: UUID(uuidString: "a38ed22d-f7b3-4d4a-804e-60512b0385cb")!,
                      sender: "鈴木 一郎 <suzuki@example.com>",
                      recipient: "高橋 健 <takahashi@example.com>",
                      subject: "お礼",
                      body: "先日のミーティングでは貴重な時間をいただきありがとうございました。",
                      isRead: false,
                      timestamp: Date(timeIntervalSinceNow: -7200)),
                .init(id: UUID(uuidString: "a7c796e3-8efd-4dd5-8527-cc23c2ce89b2")!,
                      sender: "佐藤 花子 <sato@example.com>",
                      recipient: "山本 美咲 <yamamoto@example.com>",
                      subject: "資料送付のお願い",
                      body: "前回お話しした資料を送付していただけますでしょうか。",
                      isRead: false,
                      timestamp: Date(timeIntervalSinceNow: -10800)),
                .init(id: UUID(uuidString: "90d38f9a-775a-4243-af91-726526cc6eae")!,
                      sender: "高橋 健 <takahashi@example.com>",
                      recipient: "斉藤 和也 <saito@example.com>",
                      subject: "次回の打ち合わせについて",
                      body: "次回の打ち合わせの候補日時を教えてください。",
                      isRead: false,
                      timestamp: Date(timeIntervalSinceNow: -14400)),
                .init(id: UUID(uuidString: "eb630d89-23f3-4649-a9ba-effc2cc812ad")!,
                      sender: "斉藤 和也 <saito@example.com>",
                      recipient: "田中 太郎 <tanaka@example.com>",
                      subject: "確認事項",
                      body: "こちらの内容について確認をお願いできますか？",
                      isRead: false,
                      timestamp: Date(timeIntervalSinceNow: -18000)),
                .init(id: UUID(uuidString: "ed4e1fbc-f3da-461b-8932-24fe7e2b219d")!,
                      sender: "山本 美咲 <yamamoto@example.com>",
                      recipient: "山田 太郎 <yamada@example.com>",
                      subject: "質問事項",
                      body: "いくつか質問がございますので、ご確認ください。",
                      isRead: false,
                      timestamp: Date(timeIntervalSinceNow: -21600)),
                .init(id: UUID(uuidString: "b768f111-3117-4289-8d2d-017e16e268a6")!,
                      sender: "鈴木 優子 <suzuki@example.com>",
                      recipient: "田中 次郎 <tanaka@example.com>",
                      subject: "進捗状況について",
                      body: "プロジェクトの進捗について最新情報を共有してください。",
                      isRead: false,
                      timestamp: Date(timeIntervalSinceNow: -25200)),
                .init(id: UUID(uuidString: "ca22e11e-2409-4b15-a71d-af75580957b0")!,
                      sender: "高橋 一郎 <takahashi@example.com>",
                      recipient: "佐藤 優子 <sato@example.com>",
                      subject: "お知らせ",
                      body: "来週のイベントに関するお知らせです。",
                      isRead: false,
                      timestamp: Date(timeIntervalSinceNow: -28800)),
                .init(id: UUID(uuidString: "f9dccbee-4428-4d8f-9156-d7db1452926f")!,
                      sender: "山田 花子 <yamada@example.com>",
                      recipient: "鈴木 太郎 <suzuki@example.com>",
                      subject: "お知らせ",
                      body: "このメールはお知らせのために送信されています。",
                      isRead: false,
                      timestamp: Date(timeIntervalSinceNow: -32400))]
    }
}
